# Funding options for TG Sentinel
# Uncomment and configure the platforms you want to use

# github: [redoracle]
# patreon: username
# ko_fi: username
# liberapay: username
# custom: ['https://paypal.me/username', 'https://example.com/donate']
